**NATURAL LANGUAGUE PROCESSING 232**

LAB 1: DOCUMENT CLASSIFICATION

Dang Cong Khanh

StuID: 2053105

# A. REDO THE TUTORIAL

In [ ]:
from sklearn.datasets import fetch_20newsgroups
sample_data_train = fetch_20newsgroups(subset='train', shuffle=True)

In [ ]:
print(f"Keys: {sample_data_train.keys()}")

Keys: dict_keys(['data', 'filenames', 'target_names', 'target', 'DESCR'])


In [ ]:
print(f"Data size: {len(sample_data_train.data)}")
from pprint import pprint
pprint(sample_data_train.target_names)

Data size: 11314
['alt.atheism',
 'comp.graphics',
 'comp.os.ms-windows.misc',
 'comp.sys.ibm.pc.hardware',
 'comp.sys.mac.hardware',
 'comp.windows.x',
 'misc.forsale',
 'rec.autos',
 'rec.motorcycles',
 'rec.sport.baseball',
 'rec.sport.hockey',
 'sci.crypt',
 'sci.electronics',
 'sci.med',
 'sci.space',
 'soc.religion.christian',
 'talk.politics.guns',
 'talk.politics.mideast',
 'talk.politics.misc',
 'talk.religion.misc']


In [ ]:
len(sample_data_train.data), sample_data_train.target.shape

(11314, (11314,))

In [ ]:
sample_data_train.data[:10]

["From: lerxst@wam.umd.edu (where's my thing)\nSubject: WHAT car is this!?\nNntp-Posting-Host: rac3.wam.umd.edu\nOrganization: University of Maryland, College Park\nLines: 15\n\n I was wondering if anyone out there could enlighten me on this car I saw\nthe other day. It was a 2-door sports car, looked to be from the late 60s/\nearly 70s. It was called a Bricklin. The doors were really small. In addition,\nthe front bumper was separate from the rest of the body. This is \nall I know. If anyone can tellme a model name, engine specs, years\nof production, where this car is made, history, or whatever info you\nhave on this funky looking car, please e-mail.\n\nThanks,\n- IL\n   ---- brought to you by your neighborhood Lerxst ----\n\n\n\n\n",
 "From: guykuo@carson.u.washington.edu (Guy Kuo)\nSubject: SI Clock Poll - Final Call\nSummary: Final call for SI clock reports\nKeywords: SI,acceleration,clock,upgrade\nArticle-I.D.: shelley.1qvfo9INNc3s\nOrganization: University of Washington\nLines: 

In [ ]:
[(x, sample_data_train.target_names[x]) for x in sample_data_train.target[:10]]

[(7, 'rec.autos'),
 (4, 'comp.sys.mac.hardware'),
 (4, 'comp.sys.mac.hardware'),
 (1, 'comp.graphics'),
 (14, 'sci.space'),
 (16, 'talk.politics.guns'),
 (13, 'sci.med'),
 (3, 'comp.sys.ibm.pc.hardware'),
 (2, 'comp.os.ms-windows.misc'),
 (4, 'comp.sys.mac.hardware')]

In [ ]:
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.feature_extraction.text import CountVectorizer
count_vect = CountVectorizer()
X_train_count = count_vect.fit_transform(sample_data_train.data)
tf_transformer = TfidfTransformer(use_idf=False).fit(X_train_count)
X_train_tf = tf_transformer.transform(X_train_count)
X_train_tf.shape

(11314, 130107)

In [ ]:
from sklearn import neighbors
clf = neighbors.KNeighborsClassifier()
clf.fit(X_train_tf, sample_data_train.target)

KNeighborsClassifier()

In [ ]:
test_data = [
    "hello is this me you looking for",
    "Theresa May is on the verge of publicly blaming Russia for the attempted murder of Sergei and Yulia Skripal and ordering expulsions and sanctions against President Putin’s regime. An announcement could come as early as today after a meeting of the government’s National Security Council"
]
clf.predict(test_data)

ValueError: Expected 2D array, got 1D array instead:
array=['hello is this me you looking for'
 'Theresa May is on the verge of publicly blaming Russia for the attempted murder of Sergei and Yulia Skripal and ordering expulsions and sanctions against President Putin’s regime. An announcement could come as early as today after a meeting of the government’s National Security Council'].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

# B. DOCUMENT CLASSIFICATION WITH CALIFORNIA HOUSING DATASET

I used the [California Housing dataset](https://scikit-learn.org/stable/datasets/real_world.html#california-housing-dataset) to implement document classification in this lab

I. PREPARE THE DATA

In [4]:
from sklearn.datasets import fetch_california_housing

In [5]:
california_housing = fetch_california_housing()
data, target = california_housing.data, california_housing.target

In [12]:
import numpy as np
labels = (target > np.median(target)).astype(int)

In [13]:
data_str = [" ".join(map(str, row)) for row in data]

In [14]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(data_str, labels, test_size=0.2, random_state=42)

II. Extract feature vectors

In [20]:
from sklearn.feature_extraction.text import TfidfTransformer, CountVectorizer
count_vect = CountVectorizer()
X_train_count = count_vect.fit_transform(X_train)
tf_transformer = TfidfTransformer(use_idf=False).fit(X_train_count)
X_train_tf = tf_transformer.transform(X_train_count)
X_train_tf.shape

(16512, 45744)

III. Training model

In [22]:
from sklearn import neighbors
clf = neighbors.KNeighborsClassifier()
clf.fit(X_train_tf, y_train)

KNeighborsClassifier()

IV. Prediction

In [27]:
X_test_count = count_vect.transform(X_test)
X_test_tfidf = tf_transformer.transform(X_test_count)
X_test_tfidf.shape

(4128, 45744)

In [30]:
test_label = clf.predict(X_test_tfidf)
[(x, california_housing.data[x]) for x in test_label]

[(0,
  array([   8.3252    ,   41.        ,    6.98412698,    1.02380952,
          322.        ,    2.55555556,   37.88      , -122.23      ])),
 (0,
  array([   8.3252    ,   41.        ,    6.98412698,    1.02380952,
          322.        ,    2.55555556,   37.88      , -122.23      ])),
 (1,
  array([ 8.30140000e+00,  2.10000000e+01,  6.23813708e+00,  9.71880492e-01,
          2.40100000e+03,  2.10984183e+00,  3.78600000e+01, -1.22220000e+02])),
 (1,
  array([ 8.30140000e+00,  2.10000000e+01,  6.23813708e+00,  9.71880492e-01,
          2.40100000e+03,  2.10984183e+00,  3.78600000e+01, -1.22220000e+02])),
 (0,
  array([   8.3252    ,   41.        ,    6.98412698,    1.02380952,
          322.        ,    2.55555556,   37.88      , -122.23      ])),
 (0,
  array([   8.3252    ,   41.        ,    6.98412698,    1.02380952,
          322.        ,    2.55555556,   37.88      , -122.23      ])),
 (1,
  array([ 8.30140000e+00,  2.10000000e+01,  6.23813708e+00,  9.71880492e-01,
          

V. Evaluate

In [33]:
accuracy = clf.score(X_test_tfidf, y_test)
print(f"Accuracy: {accuracy:.2f}")

Accuracy: 0.74
